import { extendTailwindMerge } from 'tailwind-merge'

const twMerge = extendTailwindMerge({
    override: {
        theme: {
            color: [
                'primary',
                'secondary',
                'tertiary',
                'quaternary',
                'active',
                'disabled',
                'disabled-subtle',
                'overlay',
                'brand',
                'brand-primary',
                'brand-secondary',
                'brand-solid',
                'brand-solid-hover',
                'error',
                'error-primary',
                'error-secondary',
                'error-subtle',
                'warning',
                'warning-primary',
                'warning-secondary',
                'success',
                'success-primary',
                'success-secondary',
                'placeholder',
                'placeholder-subtle',
                'white',
                'inherit',
            ],
            text: [
                'body-xs',
                'body-sm',
                'body-md',
                'body-lg',
                'body-xl',
                'body-[inherit]',
                'heading-level1',
                'heading-level2',
                'heading-level3',
                'heading-level4',
                'heading-level5',
                'heading-level6',
                'heading-[inherit]',
                'color-primary',
            ],
            radius: [
                'circle',
                'size-1',
                'size-2',
                'size-3',
                'size-4',
                'size-5',
                'size-6',
                'size-7',
                'size-8',
                'size-9',
                'size-10',
                'inherit',
            ],
            shadow: ['xs', 'sm', 'md', 'lg', 'xl', 'xl2', 'xl3'],
            leading: [
                'body-xs',
                'body-sm',
                'body-md',
                'body-lg',
                'body-xl',
                'heading-level1',
                'heading-level2',
                'heading-level3',
                'heading-level4',
                'heading-level5',
                'heading-level6',
            ],
            'font-weight': [
                'thin',
                'extralight',
                'light',
                'normal',
                'medium',
                'semibold',
                'bold',
                'extrabold',
                'black',
                'inherit',
            ],
        },
    },
})

export function cn(...inputs: (string | undefined | false | null)[]) {
    return twMerge(inputs.filter(Boolean).join(' '))
}
